name: CI/CD_Pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
  pull_request:

env:
  OS: 'ubuntu-latest'
  NODE_VERSION: '20'
  BUILD_DIR: build
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  # >> Continous Integration (CI) <<
  lint-and-test:
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install & Lint & Test
        run: |
          npm ci
          npm run lint
          npm run test -- --watch=false --code-coverage
      
      - name: list directory
        run: |
          ls ${{ github.workspace }}/coverage/desafio-devops/

      - name: Upload coverage report
        if: matrix.node == env.NODE_VERSION && matrix.os == env.OS
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage/desafio-devops/lcov.info

  quality-gate:
    name: Lint and Test
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Static Analysis (SonarQube)
        if: env.SONAR_TOKEN != ''
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  build:
    name: Build
    needs: quality-gate
    runs-on: ubuntu-latest
    #TODO: Uncomment to run on build or release only
    #if: startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build-node${{ env.NODE_VERSION }}
          path: ${{ env.BUILD_DIR }}/dist/

  # >> Continous Delivery (CD) <<